import { UnitymeasurementCrudComponent } from '../../pages/category/unitymeasurement/unitymeasurement-crud/unitymeasurement-crud.component';
import { BodyworkCrudComponent } from './../../pages/vehicle/bodywork/bodywork-crud/bodywork-crud.component';
import { BusinessruleUpdateComponent } from 'app/pages/bre/businessrule-update/businessrule-update.component';
import { Routes } from '@angular/router';
import { BusinessruleViewComponent } from 'app/pages/bre/businessrule-view/businessrule-view.component';
import { BusinessruleNewComponent } from 'app/pages/bre/businessrule-new/businessrule-new.component';
import { VehicleCrudComponent } from 'app/pages/vehicle/core/vehicle-crud/vehicle-crud.component';
import { VehicletypeCrudComponent } from 'app/pages/vehicle/core/vehicletype-crud/vehicletype-crud.component';
import { VehicleViewComponent } from 'app/pages/vehicle/core/vehicle-view/vehicle-view.component';
import { InitialsCrudComponent } from 'app/pages/transport/initials/initials-crud/initials-crud.component';
import { TransportViewComponent } from 'app/pages/transport/core/transport-view/transport-view.component';
import { TransportCrudComponent } from 'app/pages/transport/core/transport-crud/transport-crud.component';
import { LocationViewComponent } from 'app/pages/location/location-view/location-view.component';
import { LocationCrudComponent } from 'app/pages/location/location-crud/location-crud.component';
import { CategoryNewComponent } from 'app/pages/category/core/category-new/category-new.component';
import { CategoryViewComponent } from 'app/pages/category/core/category-view/category-view.component';
import { CategoryUpdateComponent } from 'app/pages/category/core/category-update/category-update.component';

export const AdminLayoutRoutes: Routes = [
    { path: 'location-view',       component: LocationViewComponent },
    { path: 'location-crud',       component: LocationCrudComponent },
    { path: 'vehicle-crud',        component: VehicleCrudComponent },
    { path: 'vehicle-view',        component: VehicleViewComponent },
    { path: 'vehicletype-crud',    component: VehicletypeCrudComponent },
    { path: 'category-new',        component: CategoryNewComponent },
    { path: 'category-view',       component: CategoryViewComponent },
    { path: 'category-update',     component: CategoryUpdateComponent },
    { path: 'transport-view',      component: TransportViewComponent },
    { path: 'transport-crud',      component: TransportCrudComponent },
    { path: 'bodywork-crud',       component: BodyworkCrudComponent },
    { path: 'businessrule-view',   component: BusinessruleViewComponent },
    { path: 'businessrule-new',    component: BusinessruleNewComponent },
    { path: 'businessrule-update', component: BusinessruleUpdateComponent },
    { path: 'unitymeasurement-crud', component: UnitymeasurementCrudComponent },
    { path: 'initials-crud',       component: InitialsCrudComponent }
];
